In [1]:
# Suport Vector Mechine (SVM)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset

df = pd.read_csv('datasets/shipping.csv')
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [3]:

# Convert Warehouse_block to numerical
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()


df['Warehouse_block_Encoded'] = label_encoder.fit_transform(df['Warehouse_block'])

# Convert Mode_of_Shipment to numerical

df['Mode_of_Shipment_Encoded'] = label_encoder.fit_transform(df['Mode_of_Shipment'])

# Convert Product_importance to numerical
df['Product_importance_Encoded'] = label_encoder.fit_transform(df['Product_importance'])

df['Gender_Encoded'] = label_encoder.fit_transform(df['Gender'])

df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Warehouse_block_Encoded,Mode_of_Shipment_Encoded,Product_importance_Encoded,Gender_Encoded
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,3,0,1,0
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,4,0,1,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,0,0,1,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,1,0,2,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,2,0,2,0

In [4]:
# Drop the columns that are not needed
df = df.drop(['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender'], axis=1)

correlation = df.corr()
correlation

,ID,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Warehouse_block_Encoded,Mode_of_Shipment_Encoded,Product_importance_Encoded,Gender_Encoded
ID,1.000000,0.188998,-0.005722,0.196791,0.145369,-0.598278,0.278312,-0.411822,0.000070,-0.002459,0.029081,-0.001695
Customer_care_calls,0.188998,1.000000,0.012209,0.323182,0.180771,-0.130750,-0.276615,-0.067126,0.014496,-0.020164,0.006273,0.002545
Customer_rating,-0.005722,0.012209,1.000000,0.009270,0.013179,-0.003124,-0.001897,0.013119,0.010169,0.001679,0.003157,0.002775
Cost_of_the_Product,0.196791,0.323182,0.009270,1.000000,0.123676,-0.138312,-0.132604,-0.073587,-0.006679,0.006681,0.006366,0.019759
Prior_purchases,0.145369,0.180771,0.013179,0.123676,1.000000,-0.082769,-0.168213,-0.055515,-0.005262,-0.001640,0.003662,-0.009395
Discount_offered,-0.598278,-0.130750,-0.003124,-0.138312,-0.082769,1.000000,-0.376067,0.397108,0.009569,0.009364,-0.006251,-0.011777
Weight_in_gms,0.278312,-0.276615,-0.001897,-0.132604,-0.168213,-0.376067,1.000000,-0.268793,0.004086,-0.000797,0.001652,0.003573
Reached.on.Time_Y.N,-0.411822,-0.067126,0.013119,-0.073587,-0.055515,0.397108,-0.268793,1.000000,0.005214,-0.000535,-0.023483,0.004689
Warehouse_block_Encoded,0.000070,0.014496,0.010169,-0.006679,-0.005262,0.009569,0.004086,0.005214,1.000000,0.000617,0.004260,-0.003700
Mode_of_Shipment_Encoded,-0.002459,-0.020164,0.001679,0.006681,-0.001640,0.009364,-0.000797,-0.000535,0.000617,1.000000,0.004911,-0.011288
Product_importance_Encoded,0.029081,0.006273,0.003157,0.006366,0.003662,-0.006251,0.001652,-0.023483,0.004260,0.004911,1.000000,-0.009865
Gender_Encoded,-0.001695,0.002545,0.002775,0.019759,-0.009395,-0.011777,0.003573,0.004689,-0.003700,-0.011288,-0.009865,1.000000

In [5]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing data
X = df.drop(['Reached.on.Time_Y.N', 'Discount_offered', 'Customer_care_calls', 'Customer_rating', 'Weight_in_gms'], axis=1)
print(X)

y = df['Customer_care_calls']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

          ID  Cost_of_the_Product  Prior_purchases  Warehouse_block_Encoded  \
0          1                  177                3                        3
1          2                  216                2                        4
2          3                  183                4                        0
3          4                  176                4                        1
4          5                  184                3                        2
...      ...                  ...              ...                      ...
10994  10995                  252                5                        0
10995  10996                  232                5                        1
10996  10997                  242                5                        2
10997  10998                  223                6                        4
10998  10999                  155                5                        3

       Mode_of_Shipment_Encoded  Product_importance_Encoded  Gender_Encoded
0                             0                           1               0
1                             0                           1               1
2                             0                           1               1
3                             0                           2               1
4                             0                           2               0
...                         ...                         ...             ...
10994                         2                           2               0
10995                         2                           2               0
10996                         2                           1               0
10997                         2                           2               1
10998                         2                           1               0

[10999 rows x 7 columns]

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Fitting SVM to the Training set
from sklearn.svm import SVC

classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  0  54  67   0   0   0]
 [  0 288 384   0   0   0]
 [  0 249 453   0   0   0]
 [  0 144 313   0   0   0]
 [  0  35 170   0   0   0]
 [  0   3  40   0   0   0]]

In [ ]:
# Print the accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)